# Generated by Django 4.2.16 on 2026-01-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.TextField()),
                ('senderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
