# Generated by Django 4.2.16 on 2026-01-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.TextField()),
                ('provider', models.TextField()),
                ('license', models.TextField()),
                ('capacity', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('victimId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victims.victim')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
