# Generated by Django 4.2.16 on 2026-01-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('socialMedia', models.URLField(blank=True, null=True)),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('occupation', models.TextField(blank=True, null=True)),
                ('ethnicity', models.TextField()),
                ('marital_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('SEPARATED', 'SEPARATED')], default='MARRIED')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
            options={
                'ordering': ('marital_status',),
            },
        ),
    ]
