# Generated by Django 4.2.16 on 2026-01-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.TextField()),
            ],
            options={
                'ordering': ('permission',),
            },
        ),
    ]
