# Generated by Django 5.2.8 on 2026-01-20 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('VictimId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victims.victim')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
    ]
