# Generated by Django 5.2.8 on 2026-01-20 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allegation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_plan_status', models.TextField()),
                ('response_type', models.TextField()),
                ('allegationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allegation.allegation')),
            ],
            options={
                'ordering': ('allegationId__id',),
            },
        ),
    ]
