# Generated by Django 4.2.16 on 2026-01-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
        ('reports', '0001_initial'),
        ('worker', '0001_initial'),
        ('perpetrators', '0001_initial'),
        ('abuse_type', '0001_initial'),
        ('reporters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('VictimId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victims.victim')),
                ('abuseTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuse_type.abuse')),
                ('perpetratorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpetrators.perpetrator')),
                ('reportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('reporterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporters.reporter')),
                ('workerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
            options={
                'ordering': ('startDate',),
            },
        ),
    ]
