# Generated by Django 4.2.16 on 2026-01-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('summary', models.TextField()),
                ('status', models.TextField(default='New')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reporterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporters.reporter')),
            ],
            options={
                'ordering': ('reporterId__id',),
            },
        ),
    ]
