# Generated by Django 4.2.16 on 2026-01-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('middleName', models.TextField()),
                ('maidenName', models.TextField()),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('entranceDate', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], default='M')),
            ],
            options={
                'ordering': ('firstName', 'lastName'),
            },
        ),
    ]
