# Generated by Django 4.2.16 on 2026-01-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_status', models.TextField()),
                ('attorney', models.TextField(blank=True, null=True)),
                ('petition', models.IntegerField(blank=True, null=True)),
                ('action', models.TextField()),
                ('court_action', models.TextField(blank=True, null=True)),
                ('action_type', models.TextField()),
                ('caseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
            ],
            options={
                'ordering': ('action_type',),
            },
        ),
    ]
