# Generated by Django 5.2.8 on 2026-01-20 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abuse_type', '0001_initial'),
        ('perpetrators', '0001_initial'),
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_ranking', models.IntegerField()),
                ('disposiion_code', models.CharField(choices=[('substantiated', 'substantiated'), ('indicated', 'indicated'), ('unfounded', 'unfounded')], default='unfounded')),
                ('abuse_typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuse_type.abuse')),
                ('perpetratorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpetrators.perpetrator')),
                ('victimId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victims.victim')),
            ],
            options={
                'ordering': ('abuse_typeId__id',),
            },
        ),
    ]
