# Generated by Django 4.2.16 on 2026-01-22 14:11

from django.db import migrations, models
import django.db.models.deletion
import evidence.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidenceFile', models.FileField(upload_to=evidence.models.upload_to)),
                ('evidenceFile2', models.FileField(blank=True, null=True, upload_to=evidence.models.upload_to)),
                ('evidenceFile3', models.FileField(blank=True, null=True, upload_to=evidence.models.upload_to)),
                ('evidenceFile4', models.FileField(blank=True, null=True, upload_to=evidence.models.upload_to)),
                ('reportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
